# Site settings
title: Brian Shea Hedberg
# email: briansheahedberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal site.
baseurl: "/brianshedberg" # the subpath of your site, e.g. /blog/
url: "http://gemfarmer.github.io/" # live site
# url : "http://localhost:4000/"
twitter_username: hedburglar
github_username:  gemfarmer
linkedin_username: brianshedberg

# Build settings
markdown: kramdown